### ISSUE TITLE
SearchServlet.javaのレイヤー設計方針違い

### ISSUE THREAD

**Issue by essences** [ochi9y/layerDB#1]
[SearchServlet.java](https://github.com/ochi9y/layerDB/blob/master/src/web/SearchServlet.java)

レイヤー設計上kaiinnService.searchs(key)の返り値はVOではなくBeanにしましょう。
VOからBeanへの載せ替えはServiceのレイヤーで行いましょう。

**Comment by ochi9y** [comment]
直しました
